# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99d6424fadf69ffc25f74b147784e084047cdb3b9480cb62a249704d42d8f13f3f11135214ac2ae5db7a97660bf7dce7d947eb1e89593b8fcdc3537ad56052b4

test:
  secret_key_base: 0fa0a5d0f3fbe53d258b3d52c99ae978836e10d0c91aa7c0a71f7afc76fe2b8801db88badbcc8cf2e7784edf150d7a936491ad64ca7594931e33aacfe8281fa4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
